* Encoding: UTF-8.
DATASET ACTIVATE DataSet1.
SPLIT FILE OFF.

DATASET ACTIVATE DataSet1.
CORRELATIONS
  /VARIABLES=RoundsDone COGNITIVE_TRUST_SCORE
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.

SORT CASES  BY Merkmal.
SPLIT FILE SEPARATE BY Merkmal.

DATASET ACTIVATE DataSet1.
CORRELATIONS
  /VARIABLES=RoundsDone COGNITIVE_TRUST_SCORE
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.
