* Encoding: UTF-8.
DATASET ACTIVATE DataSet1.
SPLIT FILE OFF.

EXAMINE VARIABLES=RoundsDone GENERAL_TRUST_SCORE BY Merkmal
  /PLOT BOXPLOT STEMLEAF NPPLOT
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.

SORT CASES  BY Merkmal.
SPLIT FILE SEPARATE BY Merkmal.

CORRELATIONS
  /VARIABLES=RoundsDone GENERAL_TRUST_SCORE
  /PRINT=TWOTAIL NOSIG
  /MISSING=PAIRWISE.
