using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
using Normal.Realtime;

[RealtimeModel]
public partial class IntSyncModel
{
    [RealtimeProperty(1, true, true)]
    private int _intValue;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class IntSyncModel : RealtimeModel {
    public int intValue {
        get {
            return _cache.LookForValueInCache(_intValue, entry => entry.intValueSet, entry => entry.intValue);
        }
        set {
            if (this.intValue == value) return;
            _cache.UpdateLocalCache(entry => { entry.intValueSet = true; entry.intValue = value; return entry; });
            InvalidateReliableLength();
            FireIntValueDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(IntSyncModel model, T value);
    public event PropertyChangedHandler<int> intValueDidChange;
    
    private struct LocalCacheEntry {
        public bool intValueSet;
        public int intValue;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        IntValue = 1,
    }
    
    public IntSyncModel() : this(null) {
    }
    
    public IntSyncModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireIntValueDidChange(int value) {
        try {
            intValueDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.IntValue, (uint)_intValue);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.intValueSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.IntValue, (uint)entry.intValue);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.IntValue, (uint)_intValue);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.intValueSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.intValueSet) {
                stream.WriteVarint32((uint)PropertyID.IntValue, (uint)entry.intValue);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.IntValue: {
                    int previousValue = _intValue;
                    _intValue = (int)stream.ReadVarint32();
                    bool intValueExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.intValueSet);
                    if (!intValueExistsInChangeCache && _intValue != previousValue) {
                        FireIntValueDidChange(_intValue);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _intValue = intValue;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
