using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class IntSyncModel
{
    [RealtimeProperty(1, true, true)]
    private int _intValue;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class IntSyncModel : IModel {
    // Properties
    public int intValue {
        get { return _cache.LookForValueInCache(_intValue, entry => entry.intValueSet, entry => entry.intValue); }
        set { if (value == intValue) return; _cache.UpdateLocalCache(entry => { entry.intValueSet = true; entry.intValue = value; return entry; }); FireIntValueDidChange(value); }
    }
    
    // Events
    public delegate void IntValueDidChange(IntSyncModel model, int value);
    public event         IntValueDidChange intValueDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool intValueSet;
        public int  intValue;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public IntSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireIntValueDidChange(int value) {
        try {
            if (intValueDidChange != null)
                intValueDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        IntValue = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _intValue = intValue;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.IntValue, (uint)_intValue);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.intValueSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.IntValue, (uint)entry.intValue);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.IntValue, (uint)_intValue);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.intValueSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.intValueSet)
                    stream.WriteVarint32((uint)PropertyID.IntValue, (uint)entry.intValue);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool intValueExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.intValueSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.IntValue: {
                    int previousValue = _intValue;
                    
                    _intValue = (int)stream.ReadVarint32();
                    
                    if (!intValueExistsInChangeCache && _intValue != previousValue)
                        FireIntValueDidChange(_intValue);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
