using System.Collections;
using System.Collections.Generic;
using UnityEngine;using Normal.Realtime.Serialization;
using Normal.Realtime;


    [RealtimeModel]
public partial class BoolSyncModel
{
    [RealtimeProperty(1, true, true)]
    private bool _boolValue;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class BoolSyncModel : RealtimeModel {
    public bool boolValue {
        get {
            return _cache.LookForValueInCache(_boolValue, entry => entry.boolValueSet, entry => entry.boolValue);
        }
        set {
            if (this.boolValue == value) return;
            _cache.UpdateLocalCache(entry => { entry.boolValueSet = true; entry.boolValue = value; return entry; });
            InvalidateReliableLength();
            FireBoolValueDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(BoolSyncModel model, T value);
    public event PropertyChangedHandler<bool> boolValueDidChange;
    
    private struct LocalCacheEntry {
        public bool boolValueSet;
        public bool boolValue;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache = new LocalChangeCache<LocalCacheEntry>();
    
    public enum PropertyID : uint {
        BoolValue = 1,
    }
    
    public BoolSyncModel() : this(null) {
    }
    
    public BoolSyncModel(RealtimeModel parent) : base(null, parent) {
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        UnsubscribeClearCacheCallback();
    }
    
    private void FireBoolValueDidChange(bool value) {
        try {
            boolValueDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        int length = 0;
        if (context.fullModel) {
            FlattenCache();
            length += WriteStream.WriteVarint32Length((uint)PropertyID.BoolValue, _boolValue ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.boolValueSet) {
                length += WriteStream.WriteVarint32Length((uint)PropertyID.BoolValue, entry.boolValue ? 1u : 0u);
            }
        }
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var didWriteProperties = false;
        
        if (context.fullModel) {
            stream.WriteVarint32((uint)PropertyID.BoolValue, _boolValue ? 1u : 0u);
        } else if (context.reliableChannel) {
            LocalCacheEntry entry = _cache.localCache;
            if (entry.boolValueSet) {
                _cache.PushLocalCacheToInflight(context.updateID);
                ClearCacheOnStreamCallback(context);
            }
            if (entry.boolValueSet) {
                stream.WriteVarint32((uint)PropertyID.BoolValue, entry.boolValue ? 1u : 0u);
                didWriteProperties = true;
            }
            
            if (didWriteProperties) InvalidateReliableLength();
        }
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.BoolValue: {
                    bool previousValue = _boolValue;
                    _boolValue = (stream.ReadVarint32() != 0);
                    bool boolValueExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.boolValueSet);
                    if (!boolValueExistsInChangeCache && _boolValue != previousValue) {
                        FireBoolValueDidChange(_boolValue);
                    }
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
        }
    }
    
    #region Cache Operations
    
    private StreamEventDispatcher _streamEventDispatcher;
    
    private void FlattenCache() {
        _boolValue = boolValue;
        _cache.Clear();
    }
    
    private void ClearCache(uint updateID) {
        _cache.RemoveUpdateFromInflight(updateID);
    }
    
    private void ClearCacheOnStreamCallback(StreamContext context) {
        if (_streamEventDispatcher != context.dispatcher) {
            UnsubscribeClearCacheCallback(); // unsub from previous dispatcher
        }
        _streamEventDispatcher = context.dispatcher;
        _streamEventDispatcher.AddStreamCallback(context.updateID, ClearCache);
    }
    
    private void UnsubscribeClearCacheCallback() {
        if (_streamEventDispatcher != null) {
            _streamEventDispatcher.RemoveStreamCallback(ClearCache);
            _streamEventDispatcher = null;
        }
    }
    
    #endregion
}
/* ----- End Normal Autogenerated Code ----- */
