using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TransformSyncModel
{
    [RealtimeProperty(1, true, true)]
    private Vector3 _position;
    [RealtimeProperty(2, true, true)]
    private Vector3 _rotation;
    [RealtimeProperty(3, true, true)]
    private Vector3 _scale;
}
/* ----- Begin Normal Autogenerated Code ----- */
public partial class TransformSyncModel : IModel {
    // Properties
    public UnityEngine.Vector3 position {
        get { return _cache.LookForValueInCache(_position, entry => entry.positionSet, entry => entry.position); }
        set { if (value == position) return; _cache.UpdateLocalCache(entry => { entry.positionSet = true; entry.position = value; return entry; }); FirePositionDidChange(value); }
    }
    public UnityEngine.Vector3 rotation {
        get { return _cache.LookForValueInCache(_rotation, entry => entry.rotationSet, entry => entry.rotation); }
        set { if (value == rotation) return; _cache.UpdateLocalCache(entry => { entry.rotationSet = true; entry.rotation = value; return entry; }); FireRotationDidChange(value); }
    }
    public UnityEngine.Vector3 scale {
        get { return _cache.LookForValueInCache(_scale, entry => entry.scaleSet, entry => entry.scale); }
        set { if (value == scale) return; _cache.UpdateLocalCache(entry => { entry.scaleSet = true; entry.scale = value; return entry; }); FireScaleDidChange(value); }
    }
    
    // Events
    public delegate void PositionDidChange(TransformSyncModel model, UnityEngine.Vector3 value);
    public event         PositionDidChange positionDidChange;
    public delegate void RotationDidChange(TransformSyncModel model, UnityEngine.Vector3 value);
    public event         RotationDidChange rotationDidChange;
    public delegate void ScaleDidChange(TransformSyncModel model, UnityEngine.Vector3 value);
    public event         ScaleDidChange scaleDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool                positionSet;
        public UnityEngine.Vector3 position;
        public bool                rotationSet;
        public UnityEngine.Vector3 rotation;
        public bool                scaleSet;
        public UnityEngine.Vector3 scale;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public TransformSyncModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FirePositionDidChange(UnityEngine.Vector3 value) {
        try {
            if (positionDidChange != null)
                positionDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    public void FireRotationDidChange(UnityEngine.Vector3 value) {
        try {
            if (rotationDidChange != null)
                rotationDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    public void FireScaleDidChange(UnityEngine.Vector3 value) {
        try {
            if (scaleDidChange != null)
                scaleDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Position = 1,
        Rotation = 2,
        Scale = 3,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _position = position;
            _rotation = rotation;
            _scale = scale;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteBytesLength((uint)PropertyID.Position, WriteStream.Vector3ToBytesLength());
            length += WriteStream.WriteBytesLength((uint)PropertyID.Rotation, WriteStream.Vector3ToBytesLength());
            length += WriteStream.WriteBytesLength((uint)PropertyID.Scale, WriteStream.Vector3ToBytesLength());
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.positionSet)
                    length += WriteStream.WriteBytesLength((uint)PropertyID.Position, WriteStream.Vector3ToBytesLength());
                if (entry.rotationSet)
                    length += WriteStream.WriteBytesLength((uint)PropertyID.Rotation, WriteStream.Vector3ToBytesLength());
                if (entry.scaleSet)
                    length += WriteStream.WriteBytesLength((uint)PropertyID.Scale, WriteStream.Vector3ToBytesLength());
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteBytes((uint)PropertyID.Position, WriteStream.Vector3ToBytes(_position));
            stream.WriteBytes((uint)PropertyID.Rotation, WriteStream.Vector3ToBytes(_rotation));
            stream.WriteBytes((uint)PropertyID.Scale, WriteStream.Vector3ToBytes(_scale));
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.positionSet || entry.rotationSet || entry.scaleSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.positionSet)
                    stream.WriteBytes((uint)PropertyID.Position, WriteStream.Vector3ToBytes(entry.position));
                if (entry.rotationSet)
                    stream.WriteBytes((uint)PropertyID.Rotation, WriteStream.Vector3ToBytes(entry.rotation));
                if (entry.scaleSet)
                    stream.WriteBytes((uint)PropertyID.Scale, WriteStream.Vector3ToBytes(entry.scale));
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool positionExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.positionSet);
        bool rotationExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.rotationSet);
        bool scaleExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.scaleSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Position: {
                    UnityEngine.Vector3 previousValue = _position;
                    
                    _position = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    
                    if (!positionExistsInChangeCache && _position != previousValue)
                        FirePositionDidChange(_position);
                    break;
                }
                case (uint)PropertyID.Rotation: {
                    UnityEngine.Vector3 previousValue = _rotation;
                    
                    _rotation = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    
                    if (!rotationExistsInChangeCache && _rotation != previousValue)
                        FireRotationDidChange(_rotation);
                    break;
                }
                case (uint)PropertyID.Scale: {
                    UnityEngine.Vector3 previousValue = _scale;
                    
                    _scale = ReadStream.Vector3FromBytes(stream.ReadBytes());
                    
                    if (!scaleExistsInChangeCache && _scale != previousValue)
                        FireScaleDidChange(_scale);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
