using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class AvatarSelectorModel
{
    [RealtimeProperty(1, true, true)]
    public bool _avatarNumberSelected;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class AvatarSelectorModel : IModel {
    // Properties
    public bool avatarNumberSelected {
        get { return _cache.LookForValueInCache(_avatarNumberSelected, entry => entry.avatarNumberSelectedSet, entry => entry.avatarNumberSelected); }
        set { if (value == avatarNumberSelected) return; _cache.UpdateLocalCache(entry => { entry.avatarNumberSelectedSet = true; entry.avatarNumberSelected = value; return entry; }); FireAvatarNumberSelectedDidChange(value); }
    }
    
    // Events
    public delegate void AvatarNumberSelectedDidChange(AvatarSelectorModel model, bool value);
    public event         AvatarNumberSelectedDidChange avatarNumberSelectedDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool avatarNumberSelectedSet;
        public bool avatarNumberSelected;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public AvatarSelectorModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireAvatarNumberSelectedDidChange(bool value) {
        try {
            if (avatarNumberSelectedDidChange != null)
                avatarNumberSelectedDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        AvatarNumberSelected = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _avatarNumberSelected = avatarNumberSelected;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.AvatarNumberSelected, _avatarNumberSelected ? 1u : 0u);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.avatarNumberSelectedSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.AvatarNumberSelected, entry.avatarNumberSelected ? 1u : 0u);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.AvatarNumberSelected, _avatarNumberSelected ? 1u : 0u);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.avatarNumberSelectedSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.avatarNumberSelectedSet)
                    stream.WriteVarint32((uint)PropertyID.AvatarNumberSelected, entry.avatarNumberSelected ? 1u : 0u);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool avatarNumberSelectedExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.avatarNumberSelectedSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.AvatarNumberSelected: {
                    bool previousValue = _avatarNumberSelected;
                    
                    _avatarNumberSelected = (stream.ReadVarint32() != 0);
                    
                    if (!avatarNumberSelectedExistsInChangeCache && _avatarNumberSelected != previousValue)
                        FireAvatarNumberSelectedDidChange(_avatarNumberSelected);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
