using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class ColorSyncModel
{
    [RealtimeProperty(1,false,true)]
    private Color _color;
}
/* ----- Begin Normal Autogenerated Code ----- */
public partial class ColorSyncModel : IModel {
    // Properties
    public UnityEngine.Color color {
        get { return _color; }
        set { if (value == _color) return; _colorShouldWrite = true; _color = value; FireColorDidChange(value); }
    }
    
    // Events
    public delegate void ColorDidChange(ColorSyncModel model, UnityEngine.Color value);
    public event         ColorDidChange colorDidChange;
    
    private bool _colorShouldWrite;
    
    public ColorSyncModel() {
    }
    
    // Events
    public void FireColorDidChange(UnityEngine.Color value) {
        try {
            if (colorDidChange != null)
                colorDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Color = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Write all properties
            length += WriteStream.WriteBytesLength((uint)PropertyID.Color, WriteStream.ColorToBytesLength());
        } else {
            // Unreliable properties
            if (context.unreliableChannel) {
                if (_colorShouldWrite) {
                    length += WriteStream.WriteBytesLength((uint)PropertyID.Color, WriteStream.ColorToBytesLength());
                }
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteBytes((uint)PropertyID.Color, WriteStream.ColorToBytes(_color));
            _colorShouldWrite = false;
        } else {
            // Unreliable properties
            if (context.unreliableChannel) {
                if (_colorShouldWrite) {
                    stream.WriteBytes((uint)PropertyID.Color, WriteStream.ColorToBytes(_color));
                    _colorShouldWrite = false;
                }
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Color: {
                    UnityEngine.Color previousValue = _color;
                    
                    _color = ReadStream.ColorFromBytes(stream.ReadBytes());
                    _colorShouldWrite = false;
                    
                    if (_color != previousValue)
                        FireColorDidChange(_color);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
