* Encoding: UTF-8.

DATASET ACTIVATE DataSet2.
EXAMINE VARIABLES=TeamRoundsDone N_TeamGenTrustScore BY TeamID
  /PLOT BOXPLOT NPPLOT
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.

SORT CASES  BY TeamID.
SPLIT FILE LAYERED BY TeamID.

NONPAR CORR
  /VARIABLES=TeamRoundsDone N_TeamGenTrustScore
  /PRINT=SPEARMAN TWOTAIL NOSIG
  /MISSING=PAIRWISE.
